apiVersion: k6.io/v1alpha1
kind: PrivateLoadZone
metadata:
  name: azure-sandbox-zone
  namespace: k6-plz
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  token: grafana-k6-token
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: "500m"
      memory: 512Mi