apiVersion: k6.io/v1alpha1
kind: PrivateLoadZone
metadata:
  name: azure-sandbox-zone
  namespace: k6-plz
spec:
  token: grafana-k6-token # This matches the secret we injected manually
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: "500m"
      memory: 512Mi