apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rflorendo-novare/k3s-gitops-sandbox.git' # Change to your repo
    targetRevision: HEAD
    path: infrastructure
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: k6-plz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m